# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PickMeUp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PickMeUp
  pod 'Parse'
  pod 'AFNetworking'

  target 'PickMeUpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PickMeUpUITests' do
    # Pods for testing
  end

end
