# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PickMeUp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PickMeUp
  pod 'Parse'
  pod 'AFNetworking'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'ParseLiveQuery'
  pod 'CCBottomRefreshControl'
  pod 'CBStoreHouseRefreshControl'
  pod 'JHUD'
  
  target 'PickMeUpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PickMeUpUITests' do
    # Pods for testing
  end

end
